package com.aiticketing.entity.enums;

public enum OutboxEventType {
	TRIAGE_REQUESTED,
	ROUTING_REQUESTED,
	DUPLICATE_CHECK_REQUESTED,
	VAGUE_CHECK_REQUESTED,
	KB_SUGGESTION_REQUESTED,
	KB_DRAFT_REQUESTED
}
