spring.application.name=aiticketing
server.port=8080
frontend.url=${FRONTEND_URL}
#springdoc.show-actuator=true
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:5432/ai-ticket
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

#JWT
app.security.jwt.secret=${JWT_SECRET}
app.security.jwt.expMinutes=2
app.security.jwt.issuer=ai-ticketing
#refresh token expiry 7 days
app.security.refresh.expMinutes=10080
#cookie secure flag - false for localhost, true for HTTPS
app.security.refresh.cookie.secure=false

# SQL logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.properties.hibernate.format_sql=true

# Springdoc basic path
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html