spring.application.name=aiticketing
server.port=8080
frontend.url=${FRONTEND_URL}
#springdoc.show-actuator=true
spring.config.import=optional:file:.env[.properties]

############## DB ##############
spring.datasource.url=jdbc:postgresql://localhost:5432/ai-ticket
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

############## JWT ##############
app.security.jwt.secret=${JWT_SECRET}
#app.security.jwt.expMinutes=2
app.security.jwt.expMinutes=10
app.security.jwt.issuer=ai-ticketing
#refresh token expiry 7 days
app.security.refresh.expMinutes=10080
#cookie secure flag - false for localhost, true for HTTPS
app.security.refresh.cookie.secure=false

############## logging ##############
logging.level.com.aiticketing=DEBUG
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.properties.hibernate.format_sql=true

############## OpenAI ##############
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
#for low randomness & bettr output consistency
spring.ai.openai.chat.options.temperature=0.2
spring.ai.openai.chat.options.max-tokens=350
spring.ai.openai.embedding.options.model=text-embedding-3-small

############## Worker ##############
aiticketing.ai.worker.enabled=true
#3 seconds interval scheduler
aiticketing.ai.worker.poll-ms=3000
aiticketing.ai.worker.batch-size=10
#ai response or json parsing failure
aiticketing.ai.worker.max-retries=5
aiticketing.ai.worker.thread-pool-size=4
#Duplicate state thresholds for ai
aiticketing.ai.duplicate.confirmed-threshold=0.85
aiticketing.ai.duplicate.potential-threshold=0.65
#kb suggestion retrieval threshold to call ai
aiticketing.ai.kb-suggestion.retrieval-threshold=0.50
aiticketing.ai.kb-suggestion.top-k=3

############## Springdoc basic path ##############
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html